#pragma once

#define LOGS_VERSION_MAJOR 1
#define LOGS_VERSION_MINOR 0
#define LOGS_VERSION_PATCH 117
#define LOGS_VERSION_BUILD 0
#define LOGS_VERSION_TEXT L"1.0.117"
#define LOGS_VERSION_TEXT_A "1.0.117"
